name: Terraform Plan

on:
  push:
    branches:
      - features_mod
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout
      # =========================
      - name: Checkout code
        uses: actions/checkout@v4

      # =========================
      # Azure Login - OIDC
      # =========================
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # =========================
      # Terraform Setup
      # =========================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # =========================
      # Terraform Init
      # =========================
      - name: Terraform Init
        working-directory: Environments/dev
        run: terraform init

      # =========================
      # Terraform Format Check
      # =========================
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # =========================
      # TFLint Setup
      # =========================
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      # =========================
      # TFLint Plugin Init
      # =========================
      - name: TFLint Init
        working-directory: Environments/dev
        run: tflint --init

      # =========================
      # TFLint Scan
      # =========================
      - name: TFLint
        working-directory: Environments/dev
        run: tflint --format compact

      # =========================
      # tfsec Security Scan
      # =========================
      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: Environments/dev

      # =========================
      # Terraform Validate
      # =========================
      - name: Terraform Validate
        working-directory: Environments/dev
        run: terraform validate

      # =========================
      # Terraform Plan
      # =========================
      - name: Terraform Plan
        working-directory: Environments/dev
        run: terraform plan